document.writeln("<!DOCTYPE html>");
document.writeln("<html lang=\'en\'>");
document.writeln("<head>");
document.writeln("	<meta charset=\'UTF-8\'>");
document.writeln("	<title>foot</title>");
document.writeln("</head>");
document.writeln("<link rel=\'stylesheet\' type=\'text/css\' href=\'../../css/foot.css\'>");
document.writeln("<body>");
document.writeln("	<footer>");
document.writeln("			");
document.writeln("			<ul>");
document.writeln("				<li>");
document.writeln("					<p class=\'home\'>Home</p>");
document.writeln("					<a class=\'logo\' href=\'#\'>Data 制作团队<i>&copy; 2019</i></a>");
document.writeln("				</li>");
document.writeln("				<li>");
document.writeln("					<p class=\'services\'>Services</p>");
document.writeln("");
document.writeln("					<ul>");
document.writeln("						<li><a href=\'#\'>3D modeling</a></li>");
document.writeln("						<li><a href=\'#\'>Web development</a></li>");
document.writeln("						<li><a href=\'#\'>Mobile development</a></li>");
document.writeln("						<li><a href=\'#\'>Web &amp; Print Design</a></li>");
document.writeln("					</ul>");
document.writeln("				</li>");
document.writeln("				<li>");
document.writeln("					<p class=\'reachus\'>Reach us</p>");
document.writeln("");
document.writeln("					<ul>");
document.writeln("						<li><a href=\'#\'>Email</a></li>");
document.writeln("						<li><a href=\'#\'>Twitter</a></li>");
document.writeln("						<li><a href=\'#\'>Facebook</a></li>");
document.writeln("						<li>17639193026</li>");
document.writeln("					</ul>");
document.writeln("				</li>");
document.writeln("				<li>");
document.writeln("					<p class=\'clients\'>Clients</p>");
document.writeln("");
document.writeln("					<ul>");
document.writeln("						<li><a href=\'#\'>Login Area</a></li>");
document.writeln("						<li><a href=\'#\'>Support Center</a></li>");
document.writeln("						<li><a href=\'#\'>FAQ</a></li>");
document.writeln("					</ul>");
document.writeln("				</li>");
document.writeln("			</ul>");
document.writeln("");
document.writeln("		</footer>");
document.writeln("</body>");
document.writeln("</html>");