/*
* @Author: ND01
* @Date:   2019-02-28 21:25:56
* @Last Modified by:   ND01
* @Last Modified time: 2019-03-06 16:36:33
*/
document.writeln("<!DOCTYPE html>");
document.writeln("<html>");
document.writeln("<head>");
document.writeln("<meta charset=\'utf-8\' />");
document.writeln("<title>CSS3自适应浏览器大小导航代码 - 站长素材</title>");
document.writeln("<meta name=\'viewport\' content=\'width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0\'>");
document.writeln("");
document.writeln("<link rel=\'stylesheet\' type=\'text/css\' href=\'../../css/reset.css\'>");
document.writeln("<link rel=\'stylesheet\' type=\'text/css\' href=\'../../css/index.css\'>");
document.writeln("");
document.writeln("</head>");
document.writeln("<body style=\'background: #EDEDED;width:70%;margin:auto;\'>");
document.writeln("");
document.writeln("	<div class=\'head-login\'>");
document.writeln("		<div></div>");
document.writeln("		<div class=\'head-login-right\'>");
document.writeln("			<ul>");
document.writeln("				<li><a href=\"../../html/Login/login.html\">请先登录</a></li>");
document.writeln("				<li><a href=\"../../html/Login/login.html\">免费注册</a></li>");
document.writeln("				<li><a href=\"../../html/Login/login.html\">我的订单</a></li>");
document.writeln("				<li><a href=\"../../html/Login/login.html\">会员中心</a></li>");
document.writeln("				<li><a href=\"../../html/Login/login.html\">帮助中心</a></li>");
document.writeln("				<li style=\'border:none;\'><img src=\'img/手机.png\' alt=\'\'><a href=\"../../login.html\">微信小程序</a></li>");
document.writeln("			</ul>");
document.writeln("		</div>");
document.writeln("	</div>");
document.writeln("	<div class=\'head-logo\'>");
document.writeln("		<div class=\'head-logo-logo\'><img src=\'../../img/logo.png\' alt=\'\'></div>");
document.writeln("		<div class=\'head-logo-ordertime\'><img src=\'../../img/ordertime.png\' alt=\'\'></div>");
document.writeln("		<div class=\'head-logo-search\'>");
document.writeln("    		<form action=\'\' class=\'head-logo-parent\'>");
document.writeln("        		<input type=\'text\'>");
document.writeln("        		<input type=\'button\' value=\'搜索一下\' style=\'margin-top:0px;\'>");
document.writeln("    		</form>");
document.writeln("		</div>");
document.writeln("		<div class=\'head-logo-shopcar\'>");
document.writeln("			<div class=\'head-logo-shopcar-car\'><img src=\'../../img/shopcar.png\' alt=\'\'></div>");
document.writeln("			<div class=\'head-logo-shopcar-words\'>我的购物车</div>");
document.writeln("		</div>");
document.writeln("	</div>");
document.writeln("	<div class=\'index-nav\'>");
document.writeln("		<div class=\'index-nav-frame clearfix\'>");
document.writeln("			<!-- <div class=\'nav-line\'>");
document.writeln("				");
document.writeln("			</div>");
document.writeln("			<div class=\'nav-small\' tabindex=\'-1\'>");
document.writeln("				<div class=\'nav-small-focus\' tabindex=\'-1\'>");
document.writeln("				</div>");
document.writeln("				<img src=\'img/icon.png\'>");
document.writeln("			</div> -->");
document.writeln("			<div class=\'index-nav-frame-line active\' tabindex=\'-1\'>");
document.writeln("				首页");
document.writeln("				<div class=\'index-nav-frame-line-center\'>");
document.writeln("					<div class=\'index-nav-frame-line-li\'>");
document.writeln("						首页1");
document.writeln("					</div>");
document.writeln("					<div class=\'index-nav-frame-line-li\'>");
document.writeln("						首页2");
document.writeln("					</div>");
document.writeln("					<div class=\'index-nav-frame-line-li\'>");
document.writeln("						首页3");
document.writeln("					</div>");
document.writeln("					<div class=\'index-nav-frame-line-li\'>");
document.writeln("						首页4");
document.writeln("					</div>");
document.writeln("					<div class=\'index-nav-frame-line-li\'>");
document.writeln("						首页5");
document.writeln("					</div>");
document.writeln("				</div>");
document.writeln("				<div class=\'index-nav-frame-line-focus\' tabindex=\'-1\'></div>");
document.writeln("			</div>");
document.writeln("			<div class=\'index-nav-frame-line\' tabindex=\'-1\'>");
document.writeln("				第二页面");
document.writeln("				<div class=\'index-nav-frame-line-center\'>");
document.writeln("					<div class=\'index-nav-frame-line-li\'>");
document.writeln("						第二页面1");
document.writeln("					</div>");
document.writeln("					<div class=\'index-nav-frame-line-li\'>");
document.writeln("						第二页面2");
document.writeln("					</div>");
document.writeln("					<div class=\'index-nav-frame-line-li\'>");
document.writeln("						第二页面3");
document.writeln("					</div>");
document.writeln("					<div class=\'index-nav-frame-line-li\'>");
document.writeln("						第二页面4");
document.writeln("					</div>");
document.writeln("					<div class=\'index-nav-frame-line-li\'>");
document.writeln("						第二页面5");
document.writeln("					</div>");
document.writeln("				</div>");
document.writeln("				<div class=\'index-nav-frame-line-focus\' tabindex=\'-1\'></div>");
document.writeln("			</div>");
document.writeln("			<div class=\'index-nav-frame-line\' tabindex=\'-1\'>");
document.writeln("				第三页面");
document.writeln("				<div class=\'index-nav-frame-line-center\'>");
document.writeln("					<div class=\'index-nav-frame-line-li\'>");
document.writeln("						第三页面1");
document.writeln("					</div>");
document.writeln("					<div class=\'index-nav-frame-line-li\'>");
document.writeln("						第三页面2");
document.writeln("					</div>");
document.writeln("					<div class=\'index-nav-frame-line-li\'>");
document.writeln("						第三页面3");
document.writeln("					</div>");
document.writeln("					<div class=\'index-nav-frame-line-li\'>");
document.writeln("						第三页面4");
document.writeln("					</div>");
document.writeln("					<div class=\'index-nav-frame-line-li\'>");
document.writeln("						第三页面5");
document.writeln("					</div>");
document.writeln("				</div>");
document.writeln("				<div class=\'index-nav-frame-line-focus\' tabindex=\'-1\'></div>");
document.writeln("			</div>");
document.writeln("			<div class=\'index-nav-frame-line\' tabindex=\'-1\'>");
document.writeln("				第四页面");
document.writeln("				<div class=\'index-nav-frame-line-center\'>");
document.writeln("					");
document.writeln("					<div class=\'index-nav-frame-line-li\'>");
document.writeln("						第四页面1");
document.writeln("					</div>");
document.writeln("					<div class=\'index-nav-frame-line-li\'>");
document.writeln("						第四页面2");
document.writeln("					</div>");
document.writeln("					<div class=\'index-nav-frame-line-li\'>");
document.writeln("						第四页面3");
document.writeln("					</div>");
document.writeln("					<div class=\'index-nav-frame-line-li\'>");
document.writeln("						第四页面4");
document.writeln("					</div>");
document.writeln("					<div class=\'index-nav-frame-line-li\'>");
document.writeln("						第四页面5");
document.writeln("					</div>");
document.writeln("				</div>");
document.writeln("				<div class=\'index-nav-frame-line-focus\' tabindex=\'-1\'></div>");
document.writeln("			</div>");
document.writeln("		</div>");
document.writeln("	</div>");
document.writeln("");
document.writeln("");
document.writeln("</body>");
document.writeln("</html>");